Enhanced cartridge descriptor
IntershopCommunicationsAG/icm-gradle-plugin pull request #59
Opened 2021-07-28 11:22 UTC by stefanh1

- new property dependsOnLibs: contains a list of library names (same name-schema as in the copyLibs-Tasks)
- added version at non-project-cartridge dependencies

2021-07-28 11:32 UTC, Thomas-Bergmann approved these changes
now the version is added to the dependsOn declaration

2021-07-29 08:02 UTC, m-raab commented
Can you add one simple test, please.

2021-07-29 08:09 UTC, m-raab requested changes

2021-07-29 08:09 UTC, m-raab commented on src/main/kotlin/com/intershop/gradle/icm/tasks/WriteCartridgeDescriptor.kt
> +                    is ModuleComponentIdentifier -> {
Try this also with an Extension.

2021-08-05 19:29 UTC, m-raab approved these changes

2021-08-05 19:29 UTC, merged