92073 - update gradle
IntershopCommunicationsAG/icm-gradle-plugin pull request #87
Opened 2023-12-13 14:15 UTC by skiesewetter-intershop

2023-12-14 07:44 UTC, DevDavido requested changes

2023-12-14 07:44 UTC, DevDavido commented on README.asciidoc
After removing the deprecated `ProjectServerDirs` object, there are remaining references in this README, see `ProjectServerDirs`.

2023-12-14 07:44 UTC, DevDavido commented on README.asciidoc
Please update README for section `Version ??? requires Gradle 7.5.1!`

2023-12-14 07:44 UTC, DevDavido commented on build.gradle.kts
> -    id("io.gitlab.arturbosch.detekt") version "1.18.0"
Please remove the `detekt.yml` configuration file too

2023-12-14 07:44 UTC, DevDavido commented on build.gradle.kts
> +    compileOnly("org.apache.ant:ant:1.10.14")
Is there any usage of the `ant` dependency or can this be removed?

2023-12-14 07:44 UTC, DevDavido commented on src/main/kotlin/com/intershop/gradle/icm/extension/DevelopmentConfiguration.kt
> -    /**
Please remove all the license configuration related documentation from README too.

2023-12-14 08:25 UTC, DevDavido approved these changes

2024-01-08 11:30 UTC, cortlepp-intershop approved these changes

2024-01-10 07:16 UTC, merged